[package]

name = "strophe"
license = "MIT"
version = "0.0.1"
authors = ["Cristian Kubis <cristian.kubis@tsunix.de>"]
description = "Rust bindings for libstrophe a simple, lightweight library for writing XMPP clients."
documentation = "https://github.com/tsurai/libstrophe-rs"
homepage = "https://github.com/tsurai/libstrophe-rs"
repository = "https://github.com/tsurai/libstrophe-rs"
readme = "README.md"
keywords = ["strophe","libstrophe", "xmpp"]
build = "build.rs"

[dependencies]
libc = "*"

[build-dependencies]
pkg-config = "0.3.2"

[lib]
name = "strophe"
